do not resolve redis IP, but rather pass hostname to redis.Client opts
testground/sdk-go pull request #18
Opened 2020-05-27 14:39 UTC by nonsense

2020-05-27 14:43 UTC, nonsense commented
With this fix I confirmed that if Redis moves from one IP to another, sidecar continues to operate correctly (i.e. there is a retry mechanism in the redis.Client value, as long as we don't hardcode an IP, but rely on a hostname).

2020-05-28 19:01 UTC, coryschwartz requested changes
Requested change to clean up

with https://github.com/testground/testground/commit/f30d1f617f39cadfef12ad5bd153fdac4da57165 merged in the requirement for the fallback list is obsoleted. I think this can be merged once the unused constants are removed.

2020-05-28 19:01 UTC, coryschwartz commented on sync/client.go
> -	var tryHosts []string
When removing this fallback, do we make sure the host is always reachable by the EnvRedisHost?

2020-05-28 19:01 UTC, coryschwartz commented on sync/client.go
>  	"sync"
A few lines down (L21:24) are are unused constants RedisHostname and HostHostname

2020-05-28 19:02 UTC, coryschwartz commented on sync/client.go
> -	var tryHosts []string
Actually, I see that it is not needed anymore in the latest testground master.

2020-05-28 19:05 UTC, nonsense commented on sync/client.go
> -	var tryHosts []string
The host provided at `EnvRedisHost` must be reachable - there is no way around that.

I am removing the fallback, so we have to be explicit every time we start the sidecar with the location of Redis - we are already doing that on `master`.

2020-05-28 19:06 UTC, coryschwartz commented on sync/client.go
>  	"sync"
Github doesn't let me comment on un-edited code.

2020-05-28 19:08 UTC, nonsense commented on sync/client.go
>  	"sync"
@coryschwartz I removed 2 consts, `EnvRedisHost` and `EnvRedisPost` are still used, although we have a default port setting (6379) so for now we are not really using `EnvRedisPort` from any of our code.

2020-05-28 19:21 UTC, merged

2020-06-01 11:19 UTC, raulk reviewed
A bit late to the party. This might cause a regression. The reason why we resolved the hostname into an IP is that every new Redis connection that the pool wants to create leads to a DNS lookup, which when you're running 10,000 instances x 2-3 Redis connection each, leads to a DNS lookup storm that causes a failure in most circumstances.

2020-06-01 11:58 UTC, nonsense commented
> which when you're running 10,000 instances x 2-3 Redis connection each, leads to a DNS lookup storm that causes a failure in most circumstances.

It'd be interesting to see that - if we run 10k instances, we definitely have at least 10k lookups (one for each test plan container, and there is no local DNS cache currently on k8s). I don't think it should matter much if we have 10k vs 20k-30k lookups.

2020-06-01 12:46 UTC, raulk commented
It would be fairly simple to fix this all-around: https://github.com/testground/testground/issues/1054.